from __future__ import annotations

from enum import StrEnum


class DraftActionType(StrEnum):
    NORMAL_SUMMON = "NORMAL_SUMMON"
    SPECIAL_SUMMON = "SPECIAL_SUMMON"
    ACTIVATE_EFFECT = "ACTIVATE_EFFECT"
    ACTIVATE_SPELL = "ACTIVATE_SPELL"
    ACTIVATE_TRAP = "ACTIVATE_TRAP"
    SET_SPELL_TRAP = "SET_SPELL_TRAP"
    SYNCHRO_SUMMON = "SYNCHRO_SUMMON"
    XYZ_SUMMON = "XYZ_SUMMON"
    LINK_SUMMON = "LINK_SUMMON"
    FUSION_SUMMON = "FUSION_SUMMON"
    SEND_TO_GRAVEYARD = "SEND_TO_GRAVEYARD"
    ADD_TO_HAND = "ADD_TO_HAND"
    SELECT_TARGET = "SELECT_TARGET"
    CUSTOM_ACTION = "CUSTOM_ACTION"
